//! Integration types — OAuth, API keys, and environment-variable connections.
//!
//! Ported from the OpenCode TypeScript monorepo:
//! - `packages/core/src/integration.ts` — top-level types, attempt lifecycle, events
//! - `packages/core/src/integration/connection.ts` — credential/env connection info
//! - `packages/core/src/integration/schema.ts` — branded ID types
//!
//! ## Architecture
//!
//! Integrations connect the AI agent to external services (GitHub, Slack, etc.)
//! via three authentication methods:
//!
//! - **OAuth** — stateful browser flow with prompts, attempt lifecycle, and callback
//! - **Key** — simple API-key-based authentication
//! - **Env** — environment-variable injection
//!
//! The TS source uses Effect.ts `Schema` for type definitions and branded strings.
//! This module provides equivalent Rust structs/enums with `serde` serialization
//! and tagged-enum representations for discriminated unions.

use crate::bus::{GlobalEvent, SharedBus};
use serde::{Deserialize, Serialize};
use std::sync::Arc;

// ── Branded String Identifiers ──────────────────────────────────────────────

/// Integration identifier (branded string).
///
/// # Source
/// `packages/core/src/integration/schema.ts` — `IntegrationSchema.ID`
/// (`Schema.String.pipe(Schema.brand("Integration.ID"))`)
pub type IntegrationId = String;

/// Authentication method identifier (branded string).
///
/// # Source
/// `packages/core/src/integration/schema.ts` — `IntegrationSchema.MethodID`
/// (`Schema.String.pipe(Schema.brand("Integration.MethodID"))`)
pub type MethodId = String;

/// OAuth attempt identifier (branded string).
///
/// Created with a `"con_"` prefix followed by an ascending sortable ID
/// (see [`crate::id::ascending`]).
///
/// # Source
/// `packages/core/src/integration.ts` lines 19–22 — `AttemptID`
/// (`Schema.String.pipe(Schema.brand("Integration.AttemptID"), ...)`).
pub type AttemptId = String;

/// Creates a new [`AttemptId`] with the `"con_"` prefix and an ascending
/// identifier generated by the crate's ID system.
///
/// # Source
/// `packages/core/src/integration.ts` line 21 —
/// `({ create: () => schema.make("con_" + Identifier.ascending()) })`
///
/// The TS source imports `Identifier` from `./util/identifier`, whose
/// `ascending()` returns a prefix-free sortable ID (`"{hex}{base62}"`).
/// We replicate this by calling [`crate::id::create`] directly with
/// `"con"` as the prefix string.
pub fn create_attempt_id() -> AttemptId {
    crate::id::create("con", crate::id::Direction::Ascending, None)
}

// ── When Condition ──────────────────────────────────────────────────────────

/// Comparison operator for conditional prompts.
///
/// # Source
/// `packages/core/src/integration.ts` line 27 — `Schema.Literals(["eq", "neq"])`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum WhenOp {
    /// Value is equal to the expected value.
    Eq,
    /// Value is not equal to the expected value.
    Neq,
}

/// Conditional guard for showing/hiding a prompt field.
///
/// If the value at `key` matches (or does not match) `value`, the associated
/// prompt is shown.
///
/// # Source
/// `packages/core/src/integration.ts` lines 25–28 — `Integration.When`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct When {
    /// Environment or input key to inspect.
    pub key: String,
    /// Comparison operator: equals or not-equals.
    pub op: WhenOp,
    /// Expected value to compare against.
    pub value: String,
}

// ── Prompts ─────────────────────────────────────────────────────────────────

/// A free-form text input prompt shown during OAuth setup.
///
/// # Source
/// `packages/core/src/integration.ts` lines 32–38 — `Integration.TextPrompt`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TextPrompt {
    /// Discriminant for the tagged union — always `"text"`.
    #[serde(rename = "type")]
    pub prompt_type: String,
    /// Unique key identifying this prompt field.
    pub key: String,
    /// User-facing message label.
    pub message: String,
    /// Optional placeholder text shown in the input field.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<String>,
    /// Optional condition that gates display of this prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub when: Option<When>,
}

/// A single option in a select/choice prompt.
///
/// # Source
/// `packages/core/src/integration.ts` lines 46–50 — inline struct inside `SelectPrompt.options`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SelectOption {
    /// Display label for the option.
    pub label: String,
    /// Value submitted when this option is chosen.
    pub value: String,
    /// Optional hint text displayed below the label.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hint: Option<String>,
}

/// A multiple-choice prompt shown during OAuth setup.
///
/// # Source
/// `packages/core/src/integration.ts` lines 41–54 — `Integration.SelectPrompt`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SelectPrompt {
    /// Discriminant for the tagged union — always `"select"`.
    #[serde(rename = "type")]
    pub prompt_type: String,
    /// Unique key identifying this prompt field.
    pub key: String,
    /// User-facing message label.
    pub message: String,
    /// Available choices.
    pub options: Vec<SelectOption>,
    /// Optional condition that gates display of this prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub when: Option<When>,
}

/// A user prompt shown during OAuth setup.
///
/// Discriminated on the `"type"` field per
/// `Schema.Union([TextPrompt, SelectPrompt]).pipe(Schema.toTaggedUnion("type"))`.
///
/// # Source
/// `packages/core/src/integration.ts` line 56 — `Integration.Prompt`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Prompt {
    /// Free-form text input.
    #[serde(rename = "text")]
    Text(TextPrompt),
    /// Multiple-choice selection.
    #[serde(rename = "select")]
    Select(SelectPrompt),
}

// ── Authentication Methods ──────────────────────────────────────────────────

/// OAuth 2.0 authentication method with optional configuration prompts.
///
/// # Source
/// `packages/core/src/integration.ts` lines 59–64 — `Integration.OAuthMethod`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OAuthMethod {
    /// Discriminant for the tagged union — always `"oauth"`.
    #[serde(rename = "type")]
    pub method_type: String,
    /// Unique identifier for this OAuth method.
    pub id: MethodId,
    /// User-facing label (e.g. "Sign in with GitHub").
    pub label: String,
    /// Optional prompts for additional configuration before OAuth flow.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompts: Option<Vec<Prompt>>,
}

/// API-key-based authentication method.
///
/// # Source
/// `packages/core/src/integration.ts` lines 67–71 — `Integration.KeyMethod`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KeyMethod {
    /// Discriminant for the tagged union — always `"key"`.
    #[serde(rename = "type")]
    pub method_type: String,
    /// Optional user-facing label for the key input.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

/// Environment-variable-based authentication method.
///
/// # Source
/// `packages/core/src/integration.ts` lines 73–77 — `Integration.EnvMethod`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EnvMethod {
    /// Discriminant for the tagged union — always `"env"`.
    #[serde(rename = "type")]
    pub method_type: String,
    /// Environment variable names to check for existing credentials.
    pub names: Vec<String>,
}

/// Authentication method registered for an integration.
///
/// Discriminated on the `"type"` field per
/// `Schema.Union([OAuthMethod, KeyMethod, EnvMethod]).pipe(Schema.toTaggedUnion("type"))`.
///
/// # Source
/// `packages/core/src/integration.ts` line 79 — `Integration.Method`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AuthMethod {
    /// OAuth 2.0 browser flow.
    #[serde(rename = "oauth")]
    OAuth(OAuthMethod),
    /// Simple API key entry.
    #[serde(rename = "key")]
    Key(KeyMethod),
    /// Environment variable injection.
    #[serde(rename = "env")]
    Env(EnvMethod),
}

// ── Connection Info ─────────────────────────────────────────────────────────

/// A stored credential exposed as an integration connection.
///
/// # Source
/// `packages/core/src/integration/connection.ts` lines 6–10 — `Connection.CredentialInfo`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConnectionCredentialInfo {
    /// Discriminant for the tagged union — always `"credential"`.
    #[serde(rename = "type")]
    pub connection_type: String,
    /// Credential identifier.
    pub id: String,
    /// User-facing label stored with the credential.
    pub label: String,
}

/// An environment variable detected as an active connection.
///
/// # Source
/// `packages/core/src/integration/connection.ts` lines 13–17 — `Connection.EnvInfo`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConnectionEnvInfo {
    /// Discriminant for the tagged union — always `"env"`.
    #[serde(rename = "type")]
    pub connection_type: String,
    /// Name of the environment variable.
    pub name: String,
}

/// Active connection for an integration.
///
/// Discriminated on the `"type"` field per
/// `Schema.Union([CredentialInfo, EnvInfo]).pipe(Schema.toTaggedUnion("type"))`.
///
/// # Source
/// `packages/core/src/integration/connection.ts` lines 19–22 — `Connection.Info`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ConnectionInfo {
    /// Stored credential connection (OAuth or API key).
    #[serde(rename = "credential")]
    Credential(ConnectionCredentialInfo),
    /// Environment-variable-based connection.
    #[serde(rename = "env")]
    Env(ConnectionEnvInfo),
}

// ── Top-level Integration Info ──────────────────────────────────────────────

/// Full integration snapshot: identity, available auth methods, and active
/// connections.
///
/// Returned by `Integration.list()` and `Integration.get()`.
///
/// # Source
/// `packages/core/src/integration.ts` lines 82–87 — `Integration.Info`
/// (`Schema.Class` with id, name, methods, connections)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IntegrationInfo {
    /// Integration identifier.
    pub id: IntegrationId,
    /// Human-readable name.
    pub name: String,
    /// Registered authentication methods.
    pub methods: Vec<AuthMethod>,
    /// Active connections (credentials and environment variables).
    pub connections: Vec<ConnectionInfo>,
}

// ── OAuth Implementation & Scope ────────────────────────────────────────────

/// Provider-specific OAuth configuration.
///
/// Stores the endpoints and credentials needed to initiate an OAuth flow
/// for a particular provider (e.g. GitHub, Google).
#[derive(Debug, Clone)]
pub struct OAuthImplementation {
    /// Provider name (e.g. "github", "google").
    pub provider: String,
    /// Authorization endpoint URL.
    pub authorize_url: String,
    /// Token endpoint URL.
    pub token_url: String,
    /// Client ID registered with the provider.
    pub client_id: String,
    /// OAuth scope string (space-separated permissions).
    pub scope: String,
}

/// Scope/permissions requested for an OAuth integration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OAuthScope {
    /// The integration this scope applies to.
    pub integration_id: IntegrationId,
    /// The authentication method within the integration.
    pub method_id: MethodId,
    /// Individual permission strings (e.g. "repo", "read:user").
    pub permissions: Vec<String>,
}

// ── Integration Reference ───────────────────────────────────────────────────

/// Lightweight reference to an integration (used in lists and editors).
///
/// # Source
/// `packages/core/src/integration.ts` lines 169–172 — `Integration.Ref`
/// (`{ id: ID, name: string }`)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IntegrationReference {
    /// Integration identifier.
    pub id: IntegrationId,
    /// Human-readable name.
    pub name: String,
}

// ── OAuth Attempt ───────────────────────────────────────────────────────────

/// OAuth attempt mode: automatic callback or manual code entry.
///
/// # Source
/// `packages/core/src/integration.ts` lines 93–104 — `OAuthAuthorization.mode`
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AttemptMode {
    /// The callback fires automatically (PKCE or device flow).
    Auto,
    /// The user must copy/paste an authorization code.
    Code,
}

/// Timestamps for an OAuth attempt.
///
/// # Source
/// `packages/core/src/integration.ts` lines 139–142 — inline `Time` struct
/// (`{ created: number, expires: number }`)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct AttemptTime {
    /// Unix-millisecond timestamp when the attempt was created.
    pub created: i64,
    /// Unix-millisecond timestamp when the attempt expires (10 minutes after
    /// creation in the TS source).
    pub expires: i64,
}

/// An active OAuth authorization attempt.
///
/// Returned when `Integration.connection.oauth()` starts a new browser flow.
///
/// # Source
/// `packages/core/src/integration.ts` lines 128–137 — `Integration.Attempt`
/// (`Schema.Class` with attemptID, url, instructions, mode, time)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IntegrationAttempt {
    /// Opaque attempt handle — used to query status, complete, or cancel.
    pub attempt_id: AttemptId,
    /// URL the user must visit to authorize.
    pub url: String,
    /// Instructions displayed to the user.
    pub instructions: String,
    /// Whether the flow completes automatically or requires a code.
    pub mode: AttemptMode,
    /// Creation and expiry timestamps.
    pub time: AttemptTime,
}

// ── Attempt Status ──────────────────────────────────────────────────────────

/// Timestamps carried by every attempt status variant.
///
/// # Source
/// `packages/core/src/integration.ts` lines 139–142 — reused `Time` struct
/// in `AttemptStatus` variants
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct StatusTime {
    /// Unix-millisecond timestamp when the attempt was created.
    pub created: i64,
    /// Unix-millisecond timestamp when the attempt expires.
    pub expires: i64,
}

/// The current lifecycle status of an OAuth attempt.
///
/// Discriminated on the `"status"` field per
/// `Schema.Union([pending, complete, failed, expired]).pipe(Schema.toTaggedUnion("status"))`.
///
/// # Source
/// `packages/core/src/integration.ts` lines 144–149 — `Integration.AttemptStatus`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum AttemptStatus {
    /// The attempt is in-progress; the user is still authorizing.
    #[serde(rename = "pending")]
    Pending {
        /// Creation and expiry timestamps.
        time: StatusTime,
    },
    /// The attempt succeeded and the credential was stored.
    #[serde(rename = "complete")]
    Complete {
        /// Creation and expiry timestamps.
        time: StatusTime,
    },
    /// The attempt failed with an error message.
    #[serde(rename = "failed")]
    Failed {
        /// Human-readable failure reason.
        message: String,
        /// Creation and expiry timestamps.
        time: StatusTime,
    },
    /// The attempt expired before completion (10-minute window).
    #[serde(rename = "expired")]
    Expired {
        /// Creation and expiry timestamps.
        time: StatusTime,
    },
}

// ── Error Types ─────────────────────────────────────────────────────────────

/// Returned when an OAuth attempt in `"code"` mode is completed without
/// providing the authorization code.
///
/// # Source
/// `packages/core/src/integration.ts` lines 152–154 —
/// `Integration.CodeRequiredError` (`Schema.TaggedErrorClass`)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CodeRequiredError {
    /// The attempt that requires a code.
    pub attempt_id: AttemptId,
}

/// Returned when an OAuth authorization flow fails for any reason.
///
/// The `cause` field holds the original error message.
///
/// # Source
/// `packages/core/src/integration.ts` lines 156–158 —
/// `Integration.AuthorizationError` (`Schema.TaggedErrorClass`)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthorizationError {
    /// The underlying error that caused the authorization failure.
    pub cause: String,
}

// ── Events ──────────────────────────────────────────────────────────────────

/// Event emitted when any integration's connections change.
///
/// This is a constant marker — the event carries no payload. Subscribers
/// re-fetch the integration list in response.
///
/// # Source
/// `packages/core/src/integration.ts` lines 162–167 — `Integration.Event.Updated`
/// (`EventV2.define({ type: "integration.updated", schema: {} })`)
pub const INTEGRATION_EVENT_UPDATED: &str = "integration.updated";

// ── IntegrationService ─────────────────────────────────────────────────────

/// Service for managing integrations: listing, OAuth auth flow, callback handling.
///
/// Ported from: `packages/core/src/integration.ts`
pub struct IntegrationService {
    /// Registered integration definitions
    definitions: std::collections::HashMap<IntegrationId, IntegrationInfo>,
    /// Active OAuth attempts
    attempts: std::collections::HashMap<AttemptId, IntegrationAttempt>,
    /// Stored credentials keyed by integration ID
    credentials: std::collections::HashMap<String, String>,
    /// Optional event bus for change notifications
    event_bus: Option<Arc<SharedBus>>,
}

impl IntegrationService {
    /// Create a new empty integration service.
    pub fn new() -> Self {
        Self {
            definitions: std::collections::HashMap::new(),
            attempts: std::collections::HashMap::new(),
            credentials: std::collections::HashMap::new(),
            event_bus: None,
        }
    }

    /// Create an integration service with an event bus for change notifications.
    #[must_use]
    pub fn with_event_bus(bus: Arc<SharedBus>) -> Self {
        Self {
            definitions: std::collections::HashMap::new(),
            attempts: std::collections::HashMap::new(),
            credentials: std::collections::HashMap::new(),
            event_bus: Some(bus),
        }
    }

    /// Register an integration definition.
    pub fn register(&mut self, info: IntegrationInfo) {
        self.definitions.insert(info.id.clone(), info);
        self.publish_event();
    }

    /// List all registered integrations with their connections.
    ///
    /// Returns references to integration info, scanning for active connections
    /// from environment variables.
    ///
    /// Ported from: `packages/core/src/integration.ts` — `list()`
    pub fn list(&self) -> Vec<IntegrationReference> {
        self.definitions
            .values()
            .map(|info| IntegrationReference {
                id: info.id.clone(),
                name: info.name.clone(),
            })
            .collect()
    }

    /// Get full info for a specific integration.
    ///
    /// Ported from: `packages/core/src/integration.ts` — `get()`
    pub fn get(&self, id: &str) -> Option<&IntegrationInfo> {
        self.definitions.get(id)
    }

    /// Get available connections for an integration.
    ///
    /// Scans environment variables for env-based connections.
    ///
    /// Ported from: `packages/core/src/integration/connection.ts`
    pub fn connections(&self, id: &str) -> Vec<ConnectionInfo> {
        let mut results = Vec::new();
        if let Some(info) = self.definitions.get(id) {
            for method in &info.methods {
                if let AuthMethod::Env(env_method) = method {
                    for name in &env_method.names {
                        if std::env::var(name).is_ok() {
                            results.push(ConnectionInfo::Env(ConnectionEnvInfo {
                                connection_type: "env".into(),
                                name: name.clone(),
                            }));
                        }
                    }
                }
            }
        }
        results
    }

    /// Start an OAuth authentication flow.
    ///
    /// Creates a new attempt record and returns the attempt info.
    ///
    /// Ported from: `packages/core/src/integration.ts` — `connection.oauth()`
    pub fn authenticate(
        &mut self,
        integration_id: &str,
        method_id: &str,
    ) -> Result<IntegrationAttempt, AuthorizationError> {
        let info = self
            .definitions
            .get(integration_id)
            .ok_or_else(|| AuthorizationError {
                cause: format!("integration not found: {integration_id}"),
            })?;

        let _oauth_method = info
            .methods
            .iter()
            .find_map(|m| match m {
                AuthMethod::OAuth(oa) if oa.id == method_id => Some(oa),
                _ => None,
            })
            .ok_or_else(|| AuthorizationError {
                cause: format!("OAuth method not found: {method_id}"),
            })?;

        let attempt_id = create_attempt_id();
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as i64;

        // Build authorization URL (simplified — TS uses provider-specific logic)
        let url = format!(
            "https://auth.opencode.dev/authorize?integration={}&method={}&attempt={}",
            integration_id, method_id, attempt_id
        );

        let attempt = IntegrationAttempt {
            attempt_id: attempt_id.clone(),
            url,
            instructions: format!(
                "Visit the URL to authorize {integration_id}",
            ),
            mode: AttemptMode::Auto,
            time: AttemptTime {
                created: now,
                expires: now + 600_000, // 10 minutes
            },
        };

        self.attempts.insert(attempt_id, attempt.clone());
        self.publish_event();
        Ok(attempt)
    }

    /// Start an OAuth authentication flow using provider-specific config.
    ///
    /// Uses the [`OAuthImplementation`] endpoints instead of a hardcoded URL.
    ///
    /// # Source
    /// `packages/core/src/integration.ts` — `connection.oauth()`
    pub fn authenticate_with_impl(
        &mut self,
        integration_id: &str,
        method_id: &str,
        oauth_impl: &OAuthImplementation,
        scope: Option<OAuthScope>,
    ) -> Result<IntegrationAttempt, AuthorizationError> {
        let info = self
            .definitions
            .get(integration_id)
            .ok_or_else(|| AuthorizationError {
                cause: format!("integration not found: {integration_id}"),
            })?;

        let _oauth_method = info
            .methods
            .iter()
            .find_map(|m| match m {
                AuthMethod::OAuth(oa) if oa.id == method_id => Some(oa),
                _ => None,
            })
            .ok_or_else(|| AuthorizationError {
                cause: format!("OAuth method not found: {method_id}"),
            })?;

        let attempt_id = create_attempt_id();
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as i64;

        let scope_str = scope
            .as_ref()
            .map(|s| s.permissions.join(" "))
            .unwrap_or_else(|| oauth_impl.scope.clone());

        let url = format!(
            "{}?client_id={}&scope={}&response_type=code&state={}",
            oauth_impl.authorize_url,
            oauth_impl.client_id,
            scope_str.replace(' ', "+"),
            attempt_id,
        );

        let attempt = IntegrationAttempt {
            attempt_id: attempt_id.clone(),
            url,
            instructions: format!(
                "Visit the URL to authorize {} via {}",
                integration_id, oauth_impl.provider,
            ),
            mode: AttemptMode::Auto,
            time: AttemptTime {
                created: now,
                expires: now + 600_000,
            },
        };

        self.attempts.insert(attempt_id, attempt.clone());
        self.publish_event();
        Ok(attempt)
    }

    /// Handle an OAuth callback — complete the authorization.
    ///
    /// When the attempt completes successfully, stores a credential entry
    /// keyed by integration ID.
    ///
    /// # Source
    /// `packages/core/src/integration.ts` — callback handling
    pub fn callback(
        &mut self,
        attempt_id: &str,
        code: Option<&str>,
    ) -> Result<AttemptStatus, AuthorizationError> {
        let attempt = self
            .attempts
            .get(attempt_id)
            .ok_or_else(|| AuthorizationError {
                cause: format!("attempt not found: {attempt_id}"),
            })?;

        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as i64;

        // Check expiry
        if now > attempt.time.expires {
            return Ok(AttemptStatus::Expired {
                time: StatusTime {
                    created: attempt.time.created,
                    expires: attempt.time.expires,
                },
            });
        }

        // Check if code is required
        if attempt.mode == AttemptMode::Code && code.is_none() {
            return Err(AuthorizationError {
                cause: "authorization code required".into(),
            });
        }

        // Store credential on successful completion
        let cred_value = code.unwrap_or(&attempt.attempt_id);
        self.credentials
            .insert(attempt.attempt_id.clone(), cred_value.to_string());

        self.publish_event();
        Ok(AttemptStatus::Complete {
            time: StatusTime {
                created: attempt.time.created,
                expires: attempt.time.expires,
            },
        })
    }

    /// Check for an API-key connection for the given integration.
    ///
    /// Returns the label of the first [`AuthMethod::Key`] method found,
    /// or `None` if no key method is registered.
    pub fn connection_key(&self, integration_id: &str) -> Option<String> {
        let info = self.definitions.get(integration_id)?;
        for method in &info.methods {
            if let AuthMethod::Key(key_method) = method {
                return key_method.label.clone();
            }
        }
        None
    }

    /// Retrieve a stored credential for an integration.
    ///
    /// Credentials are stored when an OAuth callback completes successfully.
    pub fn get_credential(&self, integration_id: &str) -> Option<&String> {
        self.credentials.get(integration_id)
    }

    /// Get the status of an OAuth attempt.
    pub fn attempt_status(&self, attempt_id: &str) -> Option<AttemptStatus> {
        let attempt = self.attempts.get(attempt_id)?;
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as i64;

        if now > attempt.time.expires {
            return Some(AttemptStatus::Expired {
                time: StatusTime {
                    created: attempt.time.created,
                    expires: attempt.time.expires,
                },
            });
        }

        Some(AttemptStatus::Pending {
            time: StatusTime {
                created: attempt.time.created,
                expires: attempt.time.expires,
            },
        })
    }

    /// Resolve which auth method to use for an integration.
    ///
    /// Prefers OAuth, then Key, then Env. Returns the method type string.
    pub fn resolve_auth_method(&self, integration_id: &str) -> Option<&str> {
        let info = self.definitions.get(integration_id)?;
        for method in &info.methods {
            match method {
                AuthMethod::OAuth(_) => return Some("oauth"),
                AuthMethod::Key(_) => return Some("key"),
                AuthMethod::Env(_) => return Some("env"),
            }
        }
        None
    }

    /// Cancel an in-progress OAuth attempt.
    ///
    /// Removes the attempt from the map and returns a `Failed` status.
    ///
    /// # Source
    /// `packages/core/src/integration.ts` — `cancelAttempt()`.
    pub fn cancel_attempt(
        &mut self,
        attempt_id: &str,
    ) -> Result<AttemptStatus, AuthorizationError> {
        let attempt = self
            .attempts
            .remove(attempt_id)
            .ok_or_else(|| AuthorizationError {
                cause: format!("attempt not found: {attempt_id}"),
            })?;

        self.publish_event();

        Ok(AttemptStatus::Failed {
            message: "cancelled by user".to_string(),
            time: StatusTime {
                created: attempt.time.created,
                expires: attempt.time.expires,
            },
        })
    }

    /// Remove all expired OAuth attempts from the map.
    ///
    /// Returns the IDs of the removed expired attempts.
    ///
    /// # Source
    /// `packages/core/src/integration.ts` — `scrubExpiredAttempts()`.
    pub fn scrub_expired_attempts(&mut self) -> Vec<AttemptId> {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as i64;

        let expired: Vec<AttemptId> = self
            .attempts
            .iter()
            .filter(|(_, a)| now > a.time.expires)
            .map(|(id, _)| id.clone())
            .collect();

        for id in &expired {
            self.attempts.remove(id);
        }

        if !expired.is_empty() {
            self.publish_event();
        }

        expired
    }

    fn publish_event(&self) {
        if let Some(ref bus) = self.event_bus {
            let _ = bus.publish(GlobalEvent::new(serde_json::json!({
                "type": INTEGRATION_EVENT_UPDATED,
            })));
        }
    }
}

impl Default for IntegrationService {
    fn default() -> Self {
        Self::new()
    }
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ---------------------------------------------------------------
    // When
    // ---------------------------------------------------------------

    #[test]
    fn when_serialize_eq() {
        let w = When {
            key: "region".into(),
            op: WhenOp::Eq,
            value: "us-east-1".into(),
        };
        let json = serde_json::to_string(&w).expect("serialize When");
        let parsed: serde_json::Value =
            serde_json::from_str(&json).expect("parse JSON");
        assert_eq!(parsed["key"], "region");
        assert_eq!(parsed["op"], "eq");
        assert_eq!(parsed["value"], "us-east-1");
    }

    #[test]
    fn when_deserialize_neq() {
        let json = r#"{"key":"env","op":"neq","value":"prod"}"#;
        let w: When = serde_json::from_str(json).expect("deserialize When");
        assert_eq!(w.key, "env");
        assert_eq!(w.op, WhenOp::Neq);
        assert_eq!(w.value, "prod");
    }

    #[test]
    fn when_round_trip() {
        let w = When {
            key: "foo".into(),
            op: WhenOp::Neq,
            value: "bar".into(),
        };
        let json = serde_json::to_string(&w).expect("serialize");
        let round: When = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(w, round);
    }

    // ---------------------------------------------------------------
    // Prompts + tagged union
    // ---------------------------------------------------------------

    #[test]
    fn text_prompt_serialize_minimal() {
        let p = TextPrompt {
            prompt_type: "text".into(),
            key: "subdomain".into(),
            message: "Enter your subdomain".into(),
            placeholder: None,
            when: None,
        };
        let json = serde_json::to_string(&p).expect("serialize TextPrompt");
        let parsed: serde_json::Value = serde_json::from_str(&json).expect("parse");
        assert_eq!(parsed["type"], "text");
        assert_eq!(parsed["key"], "subdomain");
    }

    #[test]
    fn text_prompt_round_trip_with_when() {
        let p = TextPrompt {
            prompt_type: "text".into(),
            key: "org".into(),
            message: "Organization".into(),
            placeholder: Some("e.g. acme-corp".into()),
            when: Some(When {
                key: "host".into(),
                op: WhenOp::Eq,
                value: "enterprise".into(),
            }),
        };
        let json = serde_json::to_string(&p).expect("serialize");
        let round: TextPrompt = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(p, round);
    }

    #[test]
    fn select_prompt_serialize() {
        let p = SelectPrompt {
            prompt_type: "select".into(),
            key: "region".into(),
            message: "Choose region".into(),
            options: vec![
                SelectOption {
                    label: "US East".into(),
                    value: "us-east-1".into(),
                    hint: Some("Northern Virginia".into()),
                },
                SelectOption {
                    label: "EU West".into(),
                    value: "eu-west-1".into(),
                    hint: None,
                },
            ],
            when: None,
        };
        let json = serde_json::to_string(&p).expect("serialize");
        let parsed: serde_json::Value = serde_json::from_str(&json).expect("parse");
        assert_eq!(parsed["type"], "select");
        assert_eq!(parsed["options"].as_array().expect("array").len(), 2);
    }

    #[test]
    fn prompt_tagged_union_deserialize_text() {
        let json = r#"{"type":"text","key":"token","message":"API Token"}"#;
        let p: Prompt = serde_json::from_str(json).expect("deserialize Prompt::Text");
        match p {
            Prompt::Text(t) => {
                assert_eq!(t.key, "token");
                assert_eq!(t.message, "API Token");
            }
            other => panic!("expected Prompt::Text, got {:?}", other),
        }
    }

    #[test]
    fn prompt_tagged_union_deserialize_select() {
        let json = r#"{"type":"select","key":"plan","message":"Plan","options":[{"label":"Free","value":"free"},{"label":"Pro","value":"pro"}]}"#;
        let p: Prompt = serde_json::from_str(json).expect("deserialize Prompt::Select");
        match p {
            Prompt::Select(s) => {
                assert_eq!(s.key, "plan");
                assert_eq!(s.options.len(), 2);
                assert_eq!(s.options[0].label, "Free");
            }
            other => panic!("expected Prompt::Select, got {:?}", other),
        }
    }

    // ---------------------------------------------------------------
    // AuthMethod tagged union
    // ---------------------------------------------------------------

    #[test]
    fn auth_method_oauth_serialize() {
        let m = OAuthMethod {
            method_type: "oauth".into(),
            id: "github-oauth".into(),
            label: "Sign in with GitHub".into(),
            prompts: None,
        };
        let auth = AuthMethod::OAuth(m);
        let json = serde_json::to_string(&auth).expect("serialize OAuth");
        let parsed: serde_json::Value = serde_json::from_str(&json).expect("parse");
        assert_eq!(parsed["type"], "oauth");
        assert_eq!(parsed["id"], "github-oauth");
    }

    #[test]
    fn auth_method_key_deserialize() {
        let json = r#"{"type":"key","label":"Enter API Key"}"#;
        let m: AuthMethod = serde_json::from_str(json).expect("deserialize Key");
        match m {
            AuthMethod::Key(k) => {
                assert_eq!(k.label, Some("Enter API Key".into()));
            }
            other => panic!("expected AuthMethod::Key, got {:?}", other),
        }
    }

    #[test]
    fn auth_method_env_deserialize() {
        let json = r#"{"type":"env","names":["GITHUB_TOKEN","GH_TOKEN"]}"#;
        let m: AuthMethod = serde_json::from_str(json).expect("deserialize Env");
        match m {
            AuthMethod::Env(e) => {
                assert_eq!(e.names, vec!["GITHUB_TOKEN", "GH_TOKEN"]);
            }
            other => panic!("expected AuthMethod::Env, got {:?}", other),
        }
    }

    // ---------------------------------------------------------------
    // ConnectionInfo tagged union
    // ---------------------------------------------------------------

    #[test]
    fn connection_info_credential_round_trip() {
        let c = ConnectionInfo::Credential(ConnectionCredentialInfo {
            connection_type: "credential".into(),
            id: "cred_abc123".into(),
            label: "my-github-token".into(),
        });
        let json = serde_json::to_string(&c).expect("serialize");
        let round: ConnectionInfo = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(c, round);
    }

    #[test]
    fn connection_info_env_round_trip() {
        let c = ConnectionInfo::Env(ConnectionEnvInfo {
            connection_type: "env".into(),
            name: "GITHUB_TOKEN".into(),
        });
        let json = serde_json::to_string(&c).expect("serialize");
        let parsed: serde_json::Value = serde_json::from_str(&json).expect("parse");
        assert_eq!(parsed["type"], "env");
        assert_eq!(parsed["name"], "GITHUB_TOKEN");
    }

    // ---------------------------------------------------------------
    // AttemptStatus tagged union
    // ---------------------------------------------------------------

    #[test]
    fn attempt_status_pending_serialize() {
        let s = AttemptStatus::Pending {
            time: StatusTime {
                created: 1000,
                expires: 1600,
            },
        };
        let json = serde_json::to_string(&s).expect("serialize");
        let parsed: serde_json::Value = serde_json::from_str(&json).expect("parse");
        assert_eq!(parsed["status"], "pending");
        assert_eq!(parsed["time"]["created"], 1000);
    }

    #[test]
    fn attempt_status_failed_deserialize() {
        let json = r#"{"status":"failed","message":"access_denied","time":{"created":2000,"expires":2600}}"#;
        let s: AttemptStatus = serde_json::from_str(json).expect("deserialize");
        match s {
            AttemptStatus::Failed { message, time } => {
                assert_eq!(message, "access_denied");
                assert_eq!(time.created, 2000);
            }
            other => panic!("expected AttemptStatus::Failed, got {:?}", other),
        }
    }

    // ---------------------------------------------------------------
    // IntegrationInfo
    // ---------------------------------------------------------------

    #[test]
    fn integration_info_round_trip() {
        let info = IntegrationInfo {
            id: "github".into(),
            name: "GitHub".into(),
            methods: vec![AuthMethod::OAuth(OAuthMethod {
                method_type: "oauth".into(),
                id: "gh-oauth".into(),
                label: "Sign in with GitHub".into(),
                prompts: None,
            })],
            connections: vec![ConnectionInfo::Credential(ConnectionCredentialInfo {
                connection_type: "credential".into(),
                id: "cred_1".into(),
                label: "personal".into(),
            })],
        };
        let json = serde_json::to_string(&info).expect("serialize");
        let round: IntegrationInfo = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(info, round);
    }

    // ---------------------------------------------------------------
    // IntegrationAttempt
    // ---------------------------------------------------------------

    #[test]
    fn integration_attempt_serialize_fields() {
        let attempt = IntegrationAttempt {
            attempt_id: "con_abc123".into(),
            url: "https://github.com/login/oauth/authorize".into(),
            instructions: "Visit the URL and authorize".into(),
            mode: AttemptMode::Code,
            time: AttemptTime {
                created: 1_000_000,
                expires: 1_600_000,
            },
        };
        let json = serde_json::to_string(&attempt).expect("serialize");
        let parsed: serde_json::Value = serde_json::from_str(&json).expect("parse");
        assert_eq!(parsed["attempt_id"], "con_abc123");
        assert_eq!(parsed["mode"], "code");
    }

    #[test]
    fn integration_attempt_mode_auto_round_trip() {
        let attempt = IntegrationAttempt {
            attempt_id: "con_xyz".into(),
            url: "https://example.com/auth".into(),
            instructions: "Authorize".into(),
            mode: AttemptMode::Auto,
            time: AttemptTime {
                created: 0,
                expires: 600_000,
            },
        };
        let json = serde_json::to_string(&attempt).expect("serialize");
        let round: IntegrationAttempt = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(round.mode, AttemptMode::Auto);
    }

    // ---------------------------------------------------------------
    // Event constant
    // ---------------------------------------------------------------

    #[test]
    fn event_updated_constant_is_correct() {
        assert_eq!(INTEGRATION_EVENT_UPDATED, "integration.updated");
    }

    // ---------------------------------------------------------------
    // create_attempt_id
    // ---------------------------------------------------------------

    #[test]
    fn create_attempt_id_has_con_prefix() {
        let id = create_attempt_id();
        assert!(
            id.starts_with("con_"),
            "attempt ID should start with 'con_', got: {id}"
        );
    }

    // ---------------------------------------------------------------
    // IntegrationService tests
    // ---------------------------------------------------------------

    fn make_github_integration() -> IntegrationInfo {
        IntegrationInfo {
            id: "github".into(),
            name: "GitHub".into(),
            methods: vec![
                AuthMethod::OAuth(OAuthMethod {
                    method_type: "oauth".into(),
                    id: "github-oauth".into(),
                    label: "Sign in with GitHub".into(),
                    prompts: None,
                }),
                AuthMethod::Env(EnvMethod {
                    method_type: "env".into(),
                    names: vec!["GITHUB_TOKEN".into()],
                }),
            ],
            connections: vec![],
        }
    }

    #[test]
    fn test_integration_service_list() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let list = svc.list();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].id, "github");
        assert_eq!(list[0].name, "GitHub");
    }

    #[test]
    fn test_integration_service_get() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let info = svc.get("github").expect("should find github");
        assert_eq!(info.name, "GitHub");

        assert!(svc.get("nonexistent").is_none());
    }

    #[test]
    fn test_integration_service_connections_env() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        // Test with env var set
        std::env::set_var("GITHUB_TOKEN", "test-token");
        let conns = svc.connections("github");
        assert!(!conns.is_empty());
        std::env::remove_var("GITHUB_TOKEN");
    }

    #[test]
    fn test_integration_service_connections_none() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        // GITHUB_TOKEN not set
        let conns = svc.connections("github");
        // May or may not have env connections depending on system
        // Just verify it doesn't panic
        let _ = conns;
    }

    #[test]
    fn test_integration_service_resolve_auth_method() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let method = svc.resolve_auth_method("github");
        assert_eq!(method, Some("oauth"));
    }

    #[test]
    fn test_integration_service_authenticate() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let attempt = svc.authenticate("github", "github-oauth")
            .expect("authenticate should succeed");

        assert!(attempt.attempt_id.starts_with("con_"));
        assert!(attempt.url.contains("github"));
        assert_eq!(attempt.mode, AttemptMode::Auto);
    }

    #[test]
    fn test_integration_service_authenticate_nonexistent() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let result = svc.authenticate("nonexistent", "some-method");
        assert!(result.is_err());
    }

    #[test]
    fn test_integration_service_callback() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let attempt = svc.authenticate("github", "github-oauth").unwrap();
        let attempt_id = attempt.attempt_id.clone();

        let status = svc.callback(&attempt_id, None)
            .expect("callback should succeed");

        match status {
            AttemptStatus::Complete { .. } => {} // expected
            other => panic!("expected Complete, got {:?}", other),
        }
    }

    #[test]
    fn test_integration_service_callback_not_found() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let result = svc.callback("con_nonexistent", None);
        assert!(result.is_err());
    }

    #[test]
    fn test_integration_service_attempt_status() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let attempt = svc.authenticate("github", "github-oauth").unwrap();
        let attempt_id = attempt.attempt_id.clone();

        let status = svc.attempt_status(&attempt_id);
        assert!(status.is_some());
        match status.unwrap() {
            AttemptStatus::Pending { .. } => {} // expected
            other => panic!("expected Pending, got {:?}", other),
        }
    }

    #[test]
    fn test_integration_service_default() {
        let svc = IntegrationService::default();
        assert!(svc.list().is_empty());
    }

    // ---------------------------------------------------------------
    // cancel_attempt
    // ---------------------------------------------------------------

    #[test]
    fn test_cancel_attempt_removes_and_returns_failed() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());
        let attempt = svc.authenticate("github", "github-oauth").unwrap();
        let id = attempt.attempt_id.clone();

        let status = svc.cancel_attempt(&id).expect("cancel should succeed");

        match status {
            AttemptStatus::Failed { message, time } => {
                assert_eq!(message, "cancelled by user");
                assert_eq!(time.created, attempt.time.created);
                assert_eq!(time.expires, attempt.time.expires);
            }
            other => panic!("expected Failed, got {other:?}"),
        }

        assert!(
            svc.attempts.get(&id).is_none(),
            "attempt should be removed after cancel"
        );
    }

    #[test]
    fn test_cancel_attempt_nonexistent_returns_error() {
        let mut svc = IntegrationService::new();
        let result = svc.cancel_attempt("con_does_not_exist");
        assert!(result.is_err());
        match result.unwrap_err() {
            AuthorizationError { cause } => {
                assert!(cause.contains("not found"));
            }
        }
    }

    // ---------------------------------------------------------------
    // scrub_expired_attempts
    // ---------------------------------------------------------------

    #[test]
    fn test_scrub_expired_attempts_removes_expired() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());
        let attempt = svc.authenticate("github", "github-oauth").unwrap();
        let id = attempt.attempt_id.clone();

        // Manually set the attempt to an expired time
        let expired_attempt = IntegrationAttempt {
            attempt_id: id.clone(),
            url: attempt.url,
            instructions: attempt.instructions,
            mode: attempt.mode,
            time: AttemptTime {
                created: 1_000_000,
                expires: 1_000_001, // well in the past
            },
        };
        svc.attempts.insert(id.clone(), expired_attempt);

        let removed = svc.scrub_expired_attempts();
        assert_eq!(removed.len(), 1);
        assert_eq!(removed[0], id);
        assert!(svc.attempts.is_empty());
    }

    #[test]
    fn test_scrub_expired_attempts_keeps_pending() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());
        let attempt = svc.authenticate("github", "github-oauth").unwrap();
        let id = attempt.attempt_id.clone();

        let removed = svc.scrub_expired_attempts();
        assert!(removed.is_empty());
        assert!(
            svc.attempts.get(&id).is_some(),
            "pending attempt should remain"
        );
    }

    #[test]
    fn test_scrub_expired_attempts_mixed() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        // First attempt: valid
        let valid = svc.authenticate("github", "github-oauth").unwrap();
        let valid_id = valid.attempt_id.clone();

        // Second attempt: expired
        let expired = svc.authenticate("github", "github-oauth").unwrap();
        let expired_id = expired.attempt_id.clone();
        svc.attempts.insert(
            expired_id.clone(),
            IntegrationAttempt {
                attempt_id: expired_id.clone(),
                url: expired.url,
                instructions: expired.instructions,
                mode: expired.mode,
                time: AttemptTime {
                    created: 1_000_000,
                    expires: 1_000_001,
                },
            },
        );

        let removed = svc.scrub_expired_attempts();
        assert_eq!(removed.len(), 1);
        assert_eq!(removed[0], expired_id);
        assert!(svc.attempts.get(&valid_id).is_some());
    }

    // ---------------------------------------------------------------
    // OAuthImplementation
    // ---------------------------------------------------------------

    #[test]
    fn oauth_implementation_fields() {
        let impl_ = OAuthImplementation {
            provider: "github".into(),
            authorize_url: "https://github.com/login/oauth/authorize".into(),
            token_url: "https://github.com/login/oauth/access_token".into(),
            client_id: "client_abc".into(),
            scope: "repo read:user".into(),
        };
        assert_eq!(impl_.provider, "github");
        assert_eq!(impl_.client_id, "client_abc");
    }

    #[test]
    fn oauth_implementation_clone() {
        let impl_ = OAuthImplementation {
            provider: "google".into(),
            authorize_url: "https://accounts.google.com/o/oauth2/auth".into(),
            token_url: "https://oauth2.googleapis.com/token".into(),
            client_id: "g_client".into(),
            scope: "openid email".into(),
        };
        let cloned = impl_.clone();
        assert_eq!(impl_.provider, cloned.provider);
        assert_eq!(impl_.token_url, cloned.token_url);
    }

    // ---------------------------------------------------------------
    // OAuthScope
    // ---------------------------------------------------------------

    #[test]
    fn oauth_scope_round_trip() {
        let scope = OAuthScope {
            integration_id: "github".into(),
            method_id: "gh-oauth".into(),
            permissions: vec!["repo".into(), "read:user".into()],
        };
        let json = serde_json::to_string(&scope).expect("serialize OAuthScope");
        let round: OAuthScope = serde_json::from_str(&json).expect("deserialize OAuthScope");
        assert_eq!(scope.integration_id, round.integration_id);
        assert_eq!(scope.permissions, round.permissions);
    }

    #[test]
    fn oauth_scope_serialize_json() {
        let scope = OAuthScope {
            integration_id: "google".into(),
            method_id: "g-oauth".into(),
            permissions: vec!["openid".into()],
        };
        let json = serde_json::to_string(&scope).expect("serialize");
        let parsed: serde_json::Value = serde_json::from_str(&json).expect("parse");
        assert_eq!(parsed["integration_id"], "google");
        assert_eq!(parsed["permissions"][0], "openid");
    }

    // ---------------------------------------------------------------
    // authenticate_with_impl
    // ---------------------------------------------------------------

    #[test]
    fn test_authenticate_with_impl_builds_correct_url() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let impl_ = OAuthImplementation {
            provider: "github".into(),
            authorize_url: "https://github.com/login/oauth/authorize".into(),
            token_url: "https://github.com/login/oauth/access_token".into(),
            client_id: "gh_client_id".into(),
            scope: "repo".into(),
        };

        let attempt = svc
            .authenticate_with_impl("github", "github-oauth", &impl_, None)
            .expect("authenticate_with_impl should succeed");

        assert!(attempt.url.contains("github.com/login/oauth/authorize"));
        assert!(attempt.url.contains("client_id=gh_client_id"));
        assert!(attempt.url.contains("scope=repo"));
        assert!(attempt.url.contains("response_type=code"));
        assert!(attempt.url.contains(&format!("state={}", attempt.attempt_id)));
    }

    #[test]
    fn test_authenticate_with_impl_with_scope() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let impl_ = OAuthImplementation {
            provider: "github".into(),
            authorize_url: "https://github.com/login/oauth/authorize".into(),
            token_url: "https://github.com/login/oauth/access_token".into(),
            client_id: "gh_client_id".into(),
            scope: "repo".into(),
        };

        let scope = OAuthScope {
            integration_id: "github".into(),
            method_id: "gh-oauth".into(),
            permissions: vec!["repo".into(), "read:user".into()],
        };

        let attempt = svc
            .authenticate_with_impl("github", "github-oauth", &impl_, Some(scope))
            .expect("authenticate_with_impl with scope should succeed");

        assert!(attempt.url.contains("repo+read%3Auser") || attempt.url.contains("repo read:user"));
    }

    #[test]
    fn test_authenticate_with_impl_integration_not_found() {
        let mut svc = IntegrationService::new();
        let impl_ = OAuthImplementation {
            provider: "github".into(),
            authorize_url: "https://example.com/auth".into(),
            token_url: "https://example.com/token".into(),
            client_id: "c".into(),
            scope: "".into(),
        };
        let result = svc.authenticate_with_impl("nonexistent", "method", &impl_, None);
        assert!(result.is_err());
        assert!(result.unwrap_err().cause.contains("not found"));
    }

    #[test]
    fn test_authenticate_with_impl_method_not_found() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let impl_ = OAuthImplementation {
            provider: "github".into(),
            authorize_url: "https://example.com/auth".into(),
            token_url: "https://example.com/token".into(),
            client_id: "c".into(),
            scope: "".into(),
        };
        let result = svc.authenticate_with_impl("github", "wrong-method", &impl_, None);
        assert!(result.is_err());
        assert!(result.unwrap_err().cause.contains("not found"));
    }

    #[test]
    fn test_authenticate_with_impl_attempt_stored() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let impl_ = OAuthImplementation {
            provider: "github".into(),
            authorize_url: "https://github.com/login/oauth/authorize".into(),
            token_url: "https://github.com/login/oauth/access_token".into(),
            client_id: "gh_client_id".into(),
            scope: "repo".into(),
        };

        let attempt = svc
            .authenticate_with_impl("github", "github-oauth", &impl_, None)
            .unwrap();

        assert!(
            svc.attempts.get(&attempt.attempt_id).is_some(),
            "attempt should be stored"
        );
    }

    // ---------------------------------------------------------------
    // connection_key
    // ---------------------------------------------------------------

    #[test]
    fn test_connection_key_returns_label() {
        let mut svc = IntegrationService::new();
        let mut info = make_github_integration();
        info.methods.push(AuthMethod::Key(KeyMethod {
            method_type: "key".into(),
            label: Some("GitHub API Key".into()),
        }));
        svc.register(info);

        let key = svc.connection_key("github");
        assert_eq!(key, Some("GitHub API Key".into()));
    }

    #[test]
    fn test_connection_key_no_key_method() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let key = svc.connection_key("github");
        assert_eq!(key, None);
    }

    #[test]
    fn test_connection_key_nonexistent_integration() {
        let svc = IntegrationService::new();
        assert_eq!(svc.connection_key("nonexistent"), None);
    }

    #[test]
    fn test_connection_key_no_label() {
        let mut svc = IntegrationService::new();
        let mut info = make_github_integration();
        info.methods.push(AuthMethod::Key(KeyMethod {
            method_type: "key".into(),
            label: None,
        }));
        svc.register(info);

        let key = svc.connection_key("github");
        assert_eq!(key, None);
    }

    // ---------------------------------------------------------------
    // credentials storage + get_credential
    // ---------------------------------------------------------------

    #[test]
    fn test_callback_stores_credential() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let attempt = svc.authenticate("github", "github-oauth").unwrap();
        let id = attempt.attempt_id.clone();

        let _status = svc.callback(&id, Some("auth_code_123")).unwrap();

        let cred = svc.get_credential(&id);
        assert_eq!(cred, Some(&"auth_code_123".to_string()));
    }

    #[test]
    fn test_callback_stores_attempt_id_when_no_code() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let attempt = svc.authenticate("github", "github-oauth").unwrap();
        let id = attempt.attempt_id.clone();

        let _status = svc.callback(&id, None).unwrap();

        let cred = svc.get_credential(&id);
        assert_eq!(cred, Some(&id));
    }

    #[test]
    fn test_get_credential_missing() {
        let svc = IntegrationService::new();
        assert_eq!(svc.get_credential("anything"), None);
    }

    #[test]
    fn test_get_credential_expired_attempt_no_store() {
        let mut svc = IntegrationService::new();
        svc.register(make_github_integration());

        let attempt = svc.authenticate("github", "github-oauth").unwrap();
        let id = attempt.attempt_id.clone();

        // Expire the attempt
        svc.attempts.insert(
            id.clone(),
            IntegrationAttempt {
                attempt_id: id.clone(),
                url: attempt.url,
                instructions: attempt.instructions,
                mode: attempt.mode,
                time: AttemptTime {
                    created: 1_000_000,
                    expires: 1_000_001,
                },
            },
        );

        let status = svc.callback(&id, None).unwrap();
        match status {
            AttemptStatus::Expired { .. } => {}
            other => panic!("expected Expired, got {other:?}"),
        }

        assert!(
            svc.get_credential(&id).is_none(),
            "expired attempt should not store credential"
        );
    }

    #[test]
    fn test_multiple_integations_credential_isolation() {
        let mut svc = IntegrationService::new();

        // Register two integrations
        svc.register(make_github_integration());
        svc.register(IntegrationInfo {
            id: "gitlab".into(),
            name: "GitLab".into(),
            methods: vec![AuthMethod::OAuth(OAuthMethod {
                method_type: "oauth".into(),
                id: "gitlab-oauth".into(),
                label: "Sign in with GitLab".into(),
                prompts: None,
            })],
            connections: vec![],
        });

        let gh_attempt = svc.authenticate("github", "github-oauth").unwrap();
        let gh_id = gh_attempt.attempt_id.clone();
        let gl_attempt = svc.authenticate("gitlab", "gitlab-oauth").unwrap();
        let gl_id = gl_attempt.attempt_id.clone();

        svc.callback(&gh_id, Some("gh_token")).unwrap();
        svc.callback(&gl_id, Some("gl_token")).unwrap();

        assert_eq!(svc.get_credential(&gh_id), Some(&"gh_token".to_string()));
        assert_eq!(svc.get_credential(&gl_id), Some(&"gl_token".to_string()));
    }
}
